#!/usr/bin/env bash
# print "Best School" 10 times but otherwise

for numero in {1..100}
do
  if (( numero % 3 == 0 && numero % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( numero % 3 == 0 ))
  then
    echo "Fizz"
  elif (( numero % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$numero"
  fi
done
